name: Disabled Old Persisch Audio Workflow

on:
  workflow_dispatch:

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - name: Disabled
        run: echo "This old workflow is disabled. Use Manual Persisch Full Audio instead."
